#!/bin/sh

for i in $(uci get autoupdater.stable.mirror)
do
 meshname=$(echo $i | awk '{gsub("/$", "", $1); gsub("/stable/sysupgrade", "", $1); n=split($1, a, "/"); printf("%s", a[n]);}')
done

if [ "${meshname}" = "unified" ]; then
 logger "Welcome to Uelzen Unified Firmware!"
 exit 0
fi

logger "Migrating FFUE-FW for ${meshname} to Uelzen Unified Firmware ..."

domain=$(echo ${meshname} | sed -e s/uelzen/uel/ -e s/celle/cel/ -e s/gifhorn/gif/)
if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 logger "No match for mesh ${domain} in /lib/gluon/domains/, setting do default (uez)."
 domain=uez
fi

logger "Selected Domain: ${domain}."

curdom=$(uci get gluon.core.domain)
if [ "${curdom}" != "${domain}" ]; then
 logger "Setting domain: ${domain}."
 uci set gluon.core.domain=${domain} ||:
 uci commit gluon ||:
 gluon-reconfigure
else
 logger "Domain ${domain} already set."
fi
