#!/bin/sh

for i in $(uci get autoupdater.stable.mirror)
do
 meshname=$(echo $i | awk '{gsub("/$", "", $1); gsub("/stable/sysupgrade", "", $1); n=split($1, a, "/"); printf("%s", a[n]);}')
done

echo "Migrating FFUE-FW for ${meshname} to Gluon Multidomain ..."

domain=$(echo ${meshname} | sed -e s/uelzen/uel/ -e s/celle/cel/ -e s/gifhorn/gif/)
if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "No match for Mesh ${domain} in /lib/gluon/domains/, setting do default domain (uez)."
 domain=uez
fi

echo "Selected Domain: ${domain}"
uci set gluon.core.switch_domain=${domain} ||:
uci commit gluon ||:
